### ISSUE TITLE
sonobuoy-test-agent: rerun failed tests

### ISSUE THREAD

**Issue by etungsten** [bottlerocket-os/bottlerocket-test-system#181]
We need to to be able to support the ability to rerun failed tests from a sonobuoy test results archive.

**Comment by webern** [comment]
@ecpullen we can de-prioritize this because I think we have a viable workaround. The user can specify `--keep-running` before starting the expensive conformance test suite. If any tests fail, the user can use kubectl exec to log in to the pod and manually rerun failed tests there.

I'm going to move this to the backlog and remove it rom #264 tracking.
