### ISSUE TITLE
bottlerocket metal instance provider

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-test-system#415]
Create a resource agent that can run metal-k8s Bottlerocket instances ~~using [tinkerbell](https://tinkerbell.org/)~~ using whatever platform we choose for our metal hosts.

**Comment by etungsten** [comment]
The nature of this issue has evolved a bit since it was created. We depend on EKS-A's tooling to provision Bottlerocket clusters and `eksctl anywhere` now sets up the tinkerbell stack for us so we don't directly interface with tinkerbell anymore. It's currently somewhat of an open question about how we want to generalize our testsys interface to accommodate the metal work that's currently going on with network bonding, static IP, changes to `net.toml`, and potential support expansion on different server providers.
