### ISSUE TITLE
ec2-resource: Provide fallback methods for unavailable instance type

### ISSUE THREAD

**Issue by ecpullen** [bottlerocket-os/bottlerocket-test-system#525]
It is possible that the desired instance type will not be available. If that is the case, the user should have the ability of providing alternative instance types that can be used.

**Comment by arnaldo2792** [comment]
I think a different approach will be to let `testsys` select the first instance type that fits the needs, the reason being that if I as the user provide "fallback" instance types there is still the chance of getting ICE'd, and then I have to clean up and start all over with different instance types. If instead we let `testsys` query EC2's API, filter out specific instances (i. e. those with GPUs, etc.), and use the first type of instance available (probably sorted by size so that smaller instances are tried first), there is no need to clean up and restart.

**Comment by webern** [comment]
> select the first instance type that fits the needs

I remember a wise engineer once cautioning against this due to the complexity involved.
